version: "3.1"

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    ports:
      - "27017:27017"
    container_name: "mongodb"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
      MONGO_DATA_DIR: /db/data
      # MONGO_LOG_DIR: /dev/null
    volumes:
      - ./db/data:/data/db
    command: mongod --bind_ip_all #--logpath=/dev/null

  api:
    build: ../../src
    links:
      - mongodb
    container_name: node-api-service
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      - NODE_ENV=production
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SWAGGER_HOST=${SWAGGER_HOST}
    depends_on:
      - mongodb
